# Generated by Django 5.1.7 on 2025-08-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
